### PR TITLE
PYTHON-4452 Fix setuptools version metadata

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Review by NoahStapp — APPROVED** [review]

**Comment by NoahStapp** [comment]
Have we seen these errors before? (https://spruce.mongodb.com/task/libmongocrypt_macos_test_python_patch_0d22179fd1aa02b7ae87db951a57b5b88647c8ae_664ddd669105d00007f01e75_24_05_22_11_56_23/logs?execution=0)

```
[2024/05/22 05:00:43.405] ==================================== ERRORS ====================================
[2024/05/22 05:00:43.405] _____________________ ERROR collecting test/test_crypto.py _____________________
[2024/05/22 05:00:43.405] test/test_crypto.py:26: in <module>
[2024/05/22 05:00:43.405]     from pymongocrypt.crypto import sign_rsaes_pkcs1_v1_5
[2024/05/22 05:00:43.405] pymongocrypt/crypto.py:71: in <module>
[2024/05/22 05:00:43.405]     def aes_256_cbc_encrypt(ctx, key, iv, input, output, bytes_written, status):
[2024/05/22 05:00:43.405] .venv/lib/python3.8/site-packages/cffi/api.py:396: in callback_decorator_wrap
[2024/05/22 05:00:43.405]     return self._backend.callback(cdecl, python_callable,
[2024/05/22 05:00:43.405] E   MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
[2024/05/22 05:00:43.405] ___________________ ERROR collecting test/test_mongocrypt.py ___________________
[2024/05/22 05:00:43.405] test/test_mongocrypt.py:31: in <module>
[2024/05/22 05:00:43.405]     import pymongocrypt.mongocrypt
[2024/05/22 05:00:43.405] pymongocrypt/mongocrypt.py:24: in <module>
[2024/05/22 05:00:43.405]     from pymongocrypt.crypto import (
[2024/05/22 05:00:43.405] pymongocrypt/crypto.py:71: in <module>
[2024/05/22 05:00:43.405]     def aes_256_cbc_encrypt(ctx, key, iv, input, output, bytes_written, status):
[2024/05/22 05:00:43.405] .venv/lib/python3.8/site-packages/cffi/api.py:396: in callback_decorator_wrap
[2024/05/22 05:00:43.405]     return self._backend.callback(cdecl, python_callable,
[2024/05/22 05:00:43.405] E   MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
[2024/05/22 05:00:43.405] =========================== short test summary info ============================
[2024/05/22 05:00:43.405] ERROR test/test_crypto.py - MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
[2024/05/22 05:00:43.405] ERROR test/test_mongocrypt.py - MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
```

**Comment by blink1073** [comment]
> Have we seen these errors before?

No, I'm trying to debug locally

**Comment by blink1073** [comment]
Ah, it is https://jira.mongodb.org/browse/PYTHON-3434.  I added a link to the build failure and put it in Needs Triage.

**Review by NoahStapp — APPROVED** [review]
Great find, thanks Steve!

**Pull request merged**
