### PR TITLE
MONGOCRYPT-668 Add pre-commit hooks to Python binding

### PR DESCRIPTION
**Pull request by NoahStapp**

### CODE REVIEW

**Comment by blink1073** [comment]
We should run this in our test runner as part of this PR, no?

**Comment by NoahStapp** [comment]
> We should run this in our test runner as part of this PR, no?

Whoops good catch, added.

**Comment by blink1073** [comment]
`./.evergreen/test.sh: line 78: pre-commit: command not found`

**Comment by blink1073** [comment]
We should skip `pre-commit` on Windows (`ERROR: Failed building wheel for shellcheck_py`).

**Comment by NoahStapp** [comment]
> We should skip `pre-commit` on Windows (`ERROR: Failed building wheel for shellcheck_py`).

Is `shellcheck_py` known to not support Windows? The failure is due to the same `urllib` error as before for macOS 10.14.

**Comment by blink1073** [comment]
> Is shellcheck_py known to not support Windows?

It has a wheel but it gets downloaded from source in pre-commit.  I think it is fine to only run pre-commit on *nix platforms.

**Review by blink1073 — APPROVED** [review]
LGTM!

**Pull request merged**
