### PR TITLE
PYTHON-4502 Add integration test with pymongo

### PR DESCRIPTION
**Pull request by blink1073**
Depends on https://github.com/mongodb-labs/drivers-evergreen-tools/pull/451

### CODE REVIEW

**Review by caseyclements — APPROVED** [review]
Does this PR contain any changes?

**Comment by blink1073** [comment]
> Does this PR contain any changes?

It adds a new test task for integration with pymongo.

**Comment by caseyclements** [comment]
Ohhhhh. The link took me to the last commit. lol (lint)

**Review by caseyclements — APPROVED** [review]
Looking even better now that I see more than linting changes!

**Pull request merged**
