### PR TITLE
PYTHON-3334 Bump min libmongocrypt version to 1.5

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Review by ShaneHarvey — CHANGES_REQUESTED** [review]
Can you bump the version in release.sh: https://github.com/mongodb/libmongocrypt/blob/39e2c77a2a/bindings/python/release.sh#L17
and update the changelog to say "Bundle libmongocrypt 1.5.0 in release wheels." too?

**Comment by blink1073** [comment]
Do we need to wait for 1.5 final to be available in evergreen?  `RuntimeError: Expected libmongocrypt version 1.5.0 or greater, found 1.5.0-pre3+20220706git1e1a956585`, which came from `/data/mci/dd505869dd52570731b137d832bcfcd6/libmongocrypt`

**Comment by ShaneHarvey** [comment]
IIUC 1.5.0 has already be tagged and released: https://github.com/mongodb/libmongocrypt/releases/tag/1.5.0

**Comment by blink1073** [comment]
Python builds are passing now

**Review by ShaneHarvey — APPROVED** [review]

**Pull request merged**
